name: Deploy detekcije obraza

on:
  workflow_run:
    workflows: ["Testiranje detekcije obraza"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Prijava na DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Sestavi Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:latest .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:${{ github.sha }} .
          
      - name: Potisni image na DockerHub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:${{ github.sha }}
          
      - name: Počisti
        run: |
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:latest
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/face-detection:${{ github.sha }}
